/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BaseModel = {
	/**
	 * @description The date and time when the workout was created.
	 * @type string, date-time
	 */
	createdAt?: string | null
	/**
	 * @description Unique identifier for the user who created the workout.
	 * @type string, uuid
	 */
	createdBy?: string | null
	/**
	 * @description The date and time when the workout was last updated.
	 * @type string | undefined, date-time
	 */
	updatedAt?: string
	/**
	 * @description The date and time when the workout was soft-deleted, if applicable.
	 * @type string, date-time
	 */
	deletedAt?: string | null
	/**
	 * @description Unique identifier for the user who soft-deleted the workout, if applicable.
	 * @type string, uuid
	 */
	deletedBy?: string | null
}
