/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BaseModel } from './BaseModel.ts'
import type { CreatorProfile } from './CreatorProfile.ts'
import type { ExerciseMuscle } from './ExerciseMuscle.ts'
import type { WorkoutData } from './WorkoutData.ts'
import type { WorkoutSummary } from './WorkoutSummary.ts'

export type BaseWorkout = BaseModel & {
	/**
	 * @description The title of the workout.
	 * @type string | undefined
	 */
	workoutTitle?: string
	/**
	 * @description A detailed description of the workout.
	 * @type string | undefined
	 */
	workoutDescription?: string
	/**
	 * @description Identifier of the workout\'s content.
	 * @type string, uuid
	 */
	workoutContentId?: string | null
	/**
	 * @description List of equipment codes used in the workout.
	 * @type array | undefined
	 */
	equipmentList?: string[]
	/**
	 * @description List of primary muscles targeted in the workout.
	 * @type array | undefined
	 */
	muscleUsage?: ExerciseMuscle[]
	/**
	 * @description Summary information about the workout.
	 * @type object | undefined
	 */
	workoutSummary?: WorkoutSummary
	/**
	 * @type array | undefined
	 */
	workoutData?: WorkoutData[]
	/**
	 * @description Represents a creator\'s profile information.
	 * @type object | undefined
	 */
	creatorProfile?: CreatorProfile
	/**
	 * @description The profile ID of the creator attributed to this workout.
	 * @type string | undefined, uuid
	 */
	creatorProfileId?: string
}
