/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Represents a social media account associated with a creator.
 */
export type CreatorSocialMediaAccount = {
	/**
	 * @description The ID of the social media platform from the predefined list.
	 * @type string | undefined
	 */
	socialMediaPlatformCode?: string
	/**
	 * @description The creator\'s username on this platform.
	 * @type string | undefined
	 */
	socialMediaAccountUsername?: string
}
