/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const creatorProfileDetailsExperienceLevelEnum = {
	Beginner: 'Beginner',
	Intermediate: 'Intermediate',
	Advanced: 'Advanced',
} as const

export type CreatorProfileDetailsExperienceLevelEnumKey =
	(typeof creatorProfileDetailsExperienceLevelEnum)[keyof typeof creatorProfileDetailsExperienceLevelEnum]

/**
 * @description Extended public profile details for a creator. Only returned when requested via ?include=details.
 */
export type CreatorProfileDetails = {
	/**
	 * @description Creator\'s height in centimeters.
	 * @type number
	 */
	heightCm?: number | null
	/**
	 * @description Creator\'s birth date (used to derive age for display).
	 * @type string, date
	 */
	birthDate?: string | null
	/**
	 * @description Creator\'s gender.
	 * @type string
	 */
	gender?: string | null
	/**
	 * @description Creator\'s fitness experience level.
	 * @type string
	 */
	experienceLevel?: CreatorProfileDetailsExperienceLevelEnumKey | null
	/**
	 * @description Creator\'s fitness goals.
	 * @type array | undefined
	 */
	fitnessGoals?: string[]
	/**
	 * @description Creator\'s current weight in kilograms.
	 * @type number
	 */
	currentWeightKg?: number | null
}
