/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MediaAsset } from './MediaAsset.ts'

export const creatorProfileLinkLayoutEnum = {
	standard: 'standard',
	featured: 'featured',
} as const

export type CreatorProfileLinkLayoutEnumKey =
	(typeof creatorProfileLinkLayoutEnum)[keyof typeof creatorProfileLinkLayoutEnum]

export const creatorProfileLinkOpenModeEnum = {
	inApp: 'inApp',
	external: 'external',
} as const

export type CreatorProfileLinkOpenModeEnumKey =
	(typeof creatorProfileLinkOpenModeEnum)[keyof typeof creatorProfileLinkOpenModeEnum]

/**
 * @description A single customizable link in a creator\'s \"link tree\".
 */
export type CreatorProfileLink = {
	/**
	 * @description Unique identifier for the link. Omit (or send an empty value) when creating a new link.
	 * @type string | undefined, uuid
	 */
	creatorProfileLinkId?: string
	/**
	 * @description The link\'s display title.
	 * @maxLength 80
	 * @type string
	 */
	title: string
	/**
	 * @description Optional secondary line shown under the title.
	 * @maxLength 120
	 * @type string
	 */
	subtitle?: string | null
	/**
	 * @description The destination URL. A bare domain is normalized to https:// on save.
	 * @maxLength 2048
	 * @type string
	 */
	url: string
	/**
	 * @description Optional icon identifier - an Ionicon name, a social platform code, or an emoji.
	 * @maxLength 64
	 * @type string
	 */
	iconName?: string | null
	/**
	 * @description Optional accent color (hex) used to style the link button/card.
	 * @maxLength 32
	 * @type string
	 */
	accentColor?: string | null
	/**
	 * @description Optional thumbnail image, used by the \"featured\" layout.
	 * @type object | undefined
	 */
	thumbnail?: MediaAsset
	/**
	 * @description Visual layout style for this link.
	 * @default "standard"
	 * @type string | undefined
	 */
	layout?: CreatorProfileLinkLayoutEnumKey
	/**
	 * @description How the link opens when tapped - inside an in-app web view or in the user\'s external browser.
	 * @default "inApp"
	 * @type string | undefined
	 */
	openMode?: CreatorProfileLinkOpenModeEnumKey
	/**
	 * @description Sort order within the link tree. Set automatically from array order on save.
	 * @type integer | undefined
	 */
	displayOrder?: number
	/**
	 * @description Whether the link is currently shown on the public profile.
	 * @default true
	 * @type boolean | undefined
	 */
	isActive?: boolean
	/**
	 * @description Total number of times this link has been opened.
	 * @minLength 0
	 * @type integer | undefined
	 */
	readonly clickCount?: number
}
