/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatorProfileDetails } from './CreatorProfileDetails.ts'
import type { CreatorProfileLink } from './CreatorProfileLink.ts'
import type { CreatorSocialMediaAccount } from './CreatorSocialMediaAccount.ts'
import type { MediaAsset } from './MediaAsset.ts'

export const creatorProfileCreatorProfileTypeEnum = {
	basic: 'basic',
	system: 'system',
	verified: 'verified',
	creator: 'creator',
} as const

export type CreatorProfileCreatorProfileTypeEnumKey =
	(typeof creatorProfileCreatorProfileTypeEnum)[keyof typeof creatorProfileCreatorProfileTypeEnum]

/**
 * @description Represents a creator\'s profile information.
 */
export type CreatorProfile = {
	/**
	 * @description Unique identifier for the creator profile.
	 * @type string | undefined, uuid
	 */
	readonly creatorProfileId?: string
	/**
	 * @description Associated user ID, if applicable.
	 * @type string, uuid
	 */
	readonly userId?: string | null
	/**
	 * @description Single highest-priority badge label (verified > system > creator > basic), derived from creatorProfileFlags. This is the field to read for the verified badge: it is always one clean value.
	 * @type string | undefined
	 */
	creatorProfileType?: CreatorProfileCreatorProfileTypeEnumKey
	/**
	 * @description Raw bitwise creator badge flags: 1=System, 2=Verified, 4=Creator. Always present on reads; the admin editor reads/writes the full mask here so a profile can carry multiple badges at once. On update it is honoured only for admins; omit to leave unchanged.
	 * @type integer | undefined
	 */
	creatorProfileFlags?: number
	/**
	 * @description Creator\'s username.
	 * @type string | undefined
	 */
	userName?: string
	/**
	 * @description Creator\'s display name.
	 * @type string | undefined
	 */
	displayName?: string
	/**
	 * @description Creator\'s full name.
	 * @type string | undefined
	 */
	readonly fullName?: string
	/**
	 * @description Creator\'s profile photo.
	 * @type object | undefined
	 */
	profilePhoto?: MediaAsset
	/**
	 * @description Creator\'s profile banner image. Only included when requested via ?include=banner.
	 * @type object | undefined
	 */
	profileBanner?: MediaAsset
	/**
	 * @description Tailwind CSS class name(s) for gradient banner styling when no image is set. Only included when requested via ?include=banner.
	 * @type string | undefined
	 */
	bannerClassName?: string
	/**
	 * @description Creator\'s bio text. Only included when requested via ?include=bio. Supports simple markdown.
	 * @maxLength 800
	 * @type string | undefined
	 */
	bio?: string
	/**
	 * @description List of creator\'s social media accounts.
	 * @type array | undefined
	 */
	socialMediaAccounts?: CreatorSocialMediaAccount[]
	/**
	 * @description Bitwise flags controlling which sections are shown on the public profile: 1=WorkoutLogs, 2=Statistics, 4=MyWorkouts, 8=MyPrograms, 16=LinkTree. Always present in responses; omit when updating to leave unchanged.
	 * @type integer | undefined
	 */
	profileVisibility?: number
	/**
	 * @description The creator\'s customizable link-tree entries. Only included when requested via ?include=links.
	 * @type array | undefined
	 */
	profileLinks?: CreatorProfileLink[]
	/**
	 * @description MVP sorting for creator creator profiles.
	 * @type number | undefined
	 */
	sortWeight?: number
	/**
	 * @description Number of users following this creator profile.
	 * @minLength 0
	 * @type integer | undefined
	 */
	readonly followerCount?: number
	/**
	 * @description Number of creator profiles this user is following.
	 * @minLength 0
	 * @type integer | undefined
	 */
	readonly followingCount?: number
	/**
	 * @description The creator\'s all-time longest workout streak: the number of workout-days in the longest run with at most two rest days between sessions. Monotonic, never decreases.
	 * @minLength 0
	 * @type integer | undefined
	 */
	readonly longestStreak?: number
	/**
	 * @description Number of activities this creator has posted in the queried date range.
	 * @type integer | undefined
	 */
	readonly activityCount?: number
	/**
	 * @description Order of the pinned buddy in the list, if applicable.
	 * @type integer | undefined
	 */
	readonly pinnedOrder?: number
	/**
	 * @description Whether the current user is following this creator
	 * @type boolean | undefined
	 */
	readonly isFollowing?: boolean
	/**
	 * @description Whether this creator follows the current user back (mutual-follow gate for features like challenges)
	 * @type boolean | undefined
	 */
	readonly followsYou?: boolean
	/**
	 * @description Whether the current user gets notified when this creator posts a new public workout (per-follow bell AND the viewer\'s global followed-user workouts preference). Null when not following or anonymous.
	 * @type boolean
	 */
	readonly notifyOnNewWorkouts?: boolean | null
	/**
	 * @description ID of the creator\'s primary gym location.
	 * @type string, uuid
	 */
	primaryGymLocationId?: string | null
	/**
	 * @description Name of the creator\'s primary gym location.
	 * @type string
	 */
	readonly primaryGymLocationName?: string | null
	/**
	 * @description Lightweight presentation hint for choosing feminine creator visuals. Null when unknown or not applicable.
	 * @type boolean
	 */
	readonly isFeminine?: boolean | null
	/**
	 * @description The creator\'s chosen UI colour theme id (e.g. \"gold\", \"synthwave\", \"coquette\"). Drives the app\'s appearance for the owner and the public profile page. Premium (\"pro\") theme ids are only persisted for Pro subscribers; for everyone else the theme stays local to their device. Validated against the shared ColorTheme set; null means the default gold theme.
	 * @type string
	 */
	colorTheme?: string | null
	/**
	 * @description Extended public profile details for a creator. Only returned when requested via ?include=details.
	 * @type object | undefined
	 */
	details?: CreatorProfileDetails
}
