/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatorProfile } from './CreatorProfile.ts'
import type { ExerciseVideo } from './ExerciseVideo.ts'

export type ExerciseMedia = {
	/**
	 * @description Unique identifier for the creator profile.
	 * @type string | undefined, uuid
	 */
	creatorProfileId?: string
	/**
	 * @description Represents a creator\'s profile information.
	 * @type object | undefined
	 */
	creatorProfile?: CreatorProfile
	/**
	 * @description List of exercise videos associated with the exercise.
	 * @type array | undefined
	 */
	exerciseVideos?: ExerciseVideo[]
}
