/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ExerciseEquipment } from './ExerciseEquipment.ts'
import type { ExerciseMedia } from './ExerciseMedia.ts'
import type { ExerciseMuscle } from './ExerciseMuscle.ts'
import type { ExerciseOgData } from './ExerciseOgData.ts'

export type ExerciseListItem = {
	/**
	 * @description The user who owns the exercise, if applicable.
	 * @type string, uuid
	 */
	userId?: string | null
	/**
	 * @description Unique identifier for the exercise.
	 * @type string | undefined
	 */
	exerciseCode?: string
	/**
	 * @description Translated Primary Exercise Name for the chosen Locale
	 * @type string | undefined
	 */
	exerciseName?: string
	/**
	 * @type object | undefined
	 */
	exerciseEquipment?: ExerciseEquipment
	/**
	 * @description The exerciseTypeCode of the exercise
	 * @type string
	 */
	exerciseTypeCode?: string | null
	/**
	 * @type object
	 */
	readonly exerciseOgData?: ExerciseOgData | null
	/**
	 * @description Last update timestamp for the exercise. Used by admin tooling to detect OG data that is older than the exercise itself.
	 * @type string, date-time
	 */
	readonly updatedAt?: string | null
	/**
	 * @description Popularity rating of the exercise
	 * @minLength 0
	 * @maxLength 10
	 * @default 0
	 * @type integer | undefined
	 */
	popularityRating?: number
	/**
	 * @description Array of tag codes associated with this exercise
	 * @type array | undefined
	 */
	exerciseTags?: string[]
	/**
	 * @description Indicates if the exercise is performed with weight on each side.
	 * @type boolean
	 */
	isWeightPerSide?: boolean | null
	/**
	 * @description Indicates the exercise loads resistance with weight plates (PLATE_LOADED tag). Gates the client plate calculator. Only sent when true.
	 * @type boolean
	 */
	isPlateLoaded?: boolean | null
	/**
	 * @description Indicates the plates load at a single point (no balanced two-sided load), WEIGHT_PER_SIDE tag or a single-point-loader machine/attachment. Selects the single-stack plate view over the barbell view. Only sent when true.
	 * @type boolean
	 */
	isSingleStack?: boolean | null
	/**
	 * @description Whether the exercise is favorited by the user
	 * @type boolean
	 */
	isFavorited?: boolean | null
	/**
	 * @description The publish status of the exercise
	 * @type string
	 */
	publishStatusCode?: string | null
	/**
	 * @type array | undefined
	 */
	exerciseMuscles?: ExerciseMuscle[]
	/**
	 * @description Array of media associated with this exercise
	 * @type array | undefined
	 */
	exerciseMedia?: ExerciseMedia[]
	/**
	 * @description Array of measurement codes associated with this exercise
	 * @type array
	 */
	exerciseMeasurements?: string[] | null
	/**
	 * @description Used for sorting by most recently used exercises.
	 * @type integer | undefined
	 */
	recentOrder?: number
}
