/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const exerciseGroupTypeEnum = {
	SUPERSET: 'SUPERSET',
	INTERVAL: 'INTERVAL',
	WARMUP: 'WARMUP',
	COOLDOWN: 'COOLDOWN',
	CIRCUIT: 'CIRCUIT',
	SECTION: 'SECTION',
} as const

export type ExerciseGroupTypeEnumKey =
	(typeof exerciseGroupTypeEnum)[keyof typeof exerciseGroupTypeEnum]

/**
 * @description Represents the type of an exercise group in a workout.\n
 * @example SUPERSET
 */
export type ExerciseGroupType = ExerciseGroupTypeEnumKey | null
