/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatorProfile } from './CreatorProfile.ts'
import type { MediaAsset } from './MediaAsset.ts'

export type ExerciseVideo = {
	/**
	 * @description Unique identifier for the exercise.
	 * @type string | undefined
	 */
	readonly exerciseCode?: string
	/**
	 * @description Represents a creator\'s profile information.
	 * @type object | undefined
	 */
	creatorProfile?: CreatorProfile
	/**
	 * @type object | undefined
	 */
	videoMediaAsset?: MediaAsset
	/**
	 * @type object | undefined
	 */
	thumbnailMediaAsset?: MediaAsset
	/**
	 * @description Notes about the exercise.
	 * @type string
	 */
	notes?: string | null
	/**
	 * @description The order in which the video should be displayed.
	 * @type integer | undefined
	 */
	sortOrder?: number
}
