/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Additional data for special workout data types. Each WorkoutDataType uses a subset of these properties.
 */
export type ExerciseAdditionalData = {
	/**
	 * @description YouTube or video link for ExerciseVideo entries.
	 * @type string
	 */
	exerciseLink?: string | null
	/**
	 * @description Caption text displayed with an ExerciseVideo entry.
	 * @type string
	 */
	caption?: string | null
	/**
	 * @description Display text for a Callout entry.
	 * @type string
	 */
	message?: string | null
	/**
	 * @description Alert style for ExerciseVideo or Callout entries (info, warning, success, tip).
	 * @type string
	 */
	alertType?: string | null
	/**
	 * @description The ID of the workout import entry being processed.
	 * @type string, uuid
	 */
	workoutImportEntryId?: string | null
	/**
	 * @description The source exercise list ID for an ExerciseList entry.
	 * @type string, uuid
	 */
	exerciseListId?: string | null
	/**
	 * @description Stable placeholder slot code for an ExerciseList entry.
	 * @type string
	 */
	exerciseListSlotCode?: string | null
	/**
	 * @description Display name for an ExerciseList entry.
	 * @type string
	 */
	exerciseListName?: string | null
	/**
	 * @description Whether this ExerciseList entry was created by the program importer and carries importer-authored set schema.
	 * @type boolean
	 */
	isImportedExerciseList?: boolean | null
	/**
	 * @description Snapshot of exercises available to choose from for an ExerciseList entry.
	 * @type array
	 */
	exerciseListOptions?:
		| {
				/**
				 * @description Unique identifier for the exercise option.
				 * @type string
				 */
				exerciseCode?: string | null
				/**
				 * @description Display name for the exercise option.
				 * @type string
				 */
				exerciseName?: string | null
				/**
				 * @description Thumbnail image URL for the exercise option.
				 * @type string
				 */
				exerciseThumbnailUrl?: string | null
				/**
				 * @description Publish status code for the exercise option.
				 * @type string
				 */
				publishStatusCode?: string | null
				/**
				 * @description Creator profile ID associated with the exercise option thumbnail/media.
				 * @type string, uuid
				 */
				creatorProfileId?: string | null
				/**
				 * @description Measurement codes associated with the exercise option.
				 * @type array
				 */
				exerciseMeasurements?: string[] | null
		  }[]
		| null
	/**
	 * @description The currently selected exercise code for an ExerciseList entry.
	 * @type string
	 */
	selectedExerciseCode?: string | null
	/**
	 * @description The currently selected exercise name for an ExerciseList entry.
	 * @type string
	 */
	selectedExerciseName?: string | null
	/**
	 * @description The currently selected exercise thumbnail URL for an ExerciseList entry.
	 * @type string
	 */
	selectedExerciseThumbnailUrl?: string | null
} | null
