/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ExerciseMuscle = {
	/**
	 * @description muscleCode that belongs to this exercise
	 * @pattern ^[A-Z_]+$
	 * @type string
	 */
	muscleCode: string
	/**
	 * @description The percentage of effort targeted at this muscle in the exercise.
	 * @minLength 0
	 * @maxLength 100
	 * @type integer | undefined, int32
	 */
	targetPercentage?: number
	/**
	 * @description Indicates whether this muscle is the primary muscle used in the exercise.
	 * @type boolean | undefined
	 */
	isPrimary?: boolean
}
