/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ExerciseEquipment = {
	/**
	 * @description Array of equipment code arrays that are required for this exercise
	 * @type array | undefined
	 */
	required?: string[][]
	/**
	 * @description Array of equipment code arrays that are optional for this exercise
	 * @type array | undefined
	 */
	optional?: string[][]
}
