/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatorProfile } from './CreatorProfile.ts'
import type { MediaAsset } from './MediaAsset.ts'

export type ExerciseOgData = {
	/**
	 * @description Short description of the exercise for Open Graph.
	 * @type string | undefined
	 */
	ogShortDescription?: string
	/**
	 * @description Represents a creator\'s profile information.
	 * @type object | undefined
	 */
	creatorProfile?: CreatorProfile
	/**
	 * @type object | undefined
	 */
	ogThumbnail?: MediaAsset
	/**
	 * @type object | undefined
	 */
	ogSquareThumbnail?: MediaAsset
	/**
	 * @type object | undefined
	 */
	ogWideThumbnail?: MediaAsset
	/**
	 * @description Last update timestamp for the OG data record. Compare against the parent exercise\'s updatedAt to detect outdated OG data.
	 * @type string, date-time
	 */
	readonly updatedAt?: string | null
}
