/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Measurement } from './Measurement.ts'

export type MeasurementTemplate = Measurement & {
	/**
	 * @description The last recorded value for this measurement, if available.
	 * @type number, double
	 */
	lastRecordedValue?: number | null
	/**
	 * @description The personal best value for this measurement, if available.
	 * @type number, double
	 */
	personalBestValue?: number | null
}
