/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MediaAssetImageVariant } from './MediaAssetImageVariant.ts'
import type { MediaFrameOffsets } from './MediaFrameOffsets.ts'

export type MediaAsset = {
	/**
	 * @description Unique identifier for the media element.
	 * @type string | undefined, uuid
	 */
	mediaAssetId?: string
	/**
	 * @description Categorization of the media asset. For attachments uploaded through the activity flows this is \"IMAGE\" or \"VIDEO\", letting clients pick a photo vs. video renderer without inspecting the file format.
	 * @type string | undefined
	 */
	readonly mediaType?: string
	/**
	 * @description The name of the file, which may be useful for generating URLs or simple validations.
	 * @type string | undefined
	 */
	readonly fileName?: string
	/**
	 * @description The relative path to the file within the storage system, useful for constructing URLs.
	 * @type string | undefined
	 */
	readonly filePath?: string
	/**
	 * @description The URL to the media file, which may be useful for embedding or downloading.
	 * @type string | undefined
	 */
	readonly fileUrl?: string
	/**
	 * @description File size in bytes
	 * @type integer | undefined
	 */
	readonly fileSize?: number
	/**
	 * @description File format, extension
	 * @type string | undefined
	 */
	readonly fileFormat?: string
	/**
	 * @description Intrinsic image width in pixels. Null for non-image assets or legacy rows not yet reprocessed.
	 * @minLength 1
	 * @type integer
	 */
	readonly width?: number | null
	/**
	 * @description Intrinsic image height in pixels. Null for non-image assets or legacy rows not yet reprocessed.
	 * @minLength 1
	 * @type integer
	 */
	readonly height?: number | null
	/**
	 * @description Generated display-ready image renditions, ordered from smallest to largest.
	 * @type array
	 */
	readonly imageVariants?: MediaAssetImageVariant[] | null
	/**
	 * @description Description of the media element
	 * @type string | undefined
	 */
	readonly description?: string
	/**
	 * @description Base64 encoded hash of the thumbnail image
	 * @type string
	 */
	readonly thumbHash?: string | null
	/**
	 * @description Optional manual alignment offsets for fitting this image into the different card frames used around the app. Each frame is independent; consumers read only the frame they render and ignore the rest.
	 */
	frameOffsets?: MediaFrameOffsets
}
