/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A generated, display-ready rendition of an image media asset.
 */
export type MediaAssetImageVariant = {
	/**
	 * @description Intrinsic rendition width in pixels.
	 * @minLength 1
	 * @type integer
	 */
	width: number
	/**
	 * @description Intrinsic rendition height in pixels.
	 * @minLength 1
	 * @type integer
	 */
	height: number
	/**
	 * @description Rendition size in bytes.
	 * @minLength 0
	 * @type integer, int64
	 */
	fileSize: number
	/**
	 * @description Rendition MIME type.
	 * @type string
	 */
	fileFormat: string
	/**
	 * @description Public immutable URL for the rendition.
	 * @type string, uri
	 */
	fileUrl: string
}
