/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MediaFrameOffset } from './MediaFrameOffset.ts'

/**
 * @description Per-frame manual alignment offsets for an image. Every frame is optional, a frame that is absent falls back to the card\'s default cropping.
 */
export type MediaFrameOffsets = {
	/**
	 * @description Manual object-position offset (percentages, 0-100) describing how a cover-fit image should be aligned inside a card frame. x is the horizontal focal point (0 = left, 100 = right); y is the vertical focal point (0 = top, 100 = bottom).
	 * @type object | undefined
	 */
	listCard?: MediaFrameOffset
	/**
	 * @description Manual object-position offset (percentages, 0-100) describing how a cover-fit image should be aligned inside a card frame. x is the horizontal focal point (0 = left, 100 = right); y is the vertical focal point (0 = top, 100 = bottom).
	 * @type object | undefined
	 */
	posterTall?: MediaFrameOffset
	/**
	 * @description Manual object-position offset (percentages, 0-100) describing how a cover-fit image should be aligned inside a card frame. x is the horizontal focal point (0 = left, 100 = right); y is the vertical focal point (0 = top, 100 = bottom).
	 * @type object | undefined
	 */
	posterCompact?: MediaFrameOffset
	/**
	 * @description Manual object-position offset (percentages, 0-100) describing how a cover-fit image should be aligned inside a card frame. x is the horizontal focal point (0 = left, 100 = right); y is the vertical focal point (0 = top, 100 = bottom).
	 * @type object | undefined
	 */
	hero?: MediaFrameOffset
	/**
	 * @description Manual object-position offset (percentages, 0-100) describing how a cover-fit image should be aligned inside a card frame. x is the horizontal focal point (0 = left, 100 = right); y is the vertical focal point (0 = top, 100 = bottom).
	 * @type object | undefined
	 */
	detailHeader?: MediaFrameOffset
}
