/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Manual object-position offset (percentages, 0-100) describing how a cover-fit image should be aligned inside a card frame. x is the horizontal focal point (0 = left, 100 = right); y is the vertical focal point (0 = top, 100 = bottom).
 */
export type MediaFrameOffset = {
	/**
	 * @description Horizontal object-position percentage (0 = left, 100 = right).
	 * @type number | undefined, float
	 */
	x?: number
	/**
	 * @description Vertical object-position percentage (0 = top, 100 = bottom).
	 * @type number | undefined, float
	 */
	y?: number
}
