/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MuscleTranslation = {
	/**
	 * @description The muscle code of the translation
	 * @type string
	 */
	readonly muscleCode: string
	/**
	 * @description The locale code of the translation
	 * @type string
	 */
	localeCode: string
	/**
	 * @description The translated name of the muscle
	 * @type string | undefined
	 */
	muscleName?: string
}
