/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MuscleTranslation } from './MuscleTranslation.ts'

export type Muscle = {
	/**
	 * @description Unique identifier for the muscle
	 * @type string
	 */
	muscleCode: string
	/**
	 * @description The name of the muscle in the default language (typically English)
	 * @type string | undefined
	 */
	readonly muscleName?: string
	/**
	 * @description The friendly name of the muscle in the user\'s preferred language
	 * @type string | undefined
	 */
	readonly friendlyName?: string
	/**
	 * @type array | undefined
	 */
	muscleTranslations?: MuscleTranslation[]
}
