/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MediaAsset } from './MediaAsset.ts'
import type { MuscleGroupTranslation } from './MuscleGroupTranslation.ts'
import type { MuscleSplitTarget } from './MuscleSplitTarget.ts'

export const muscleGroupMuscleGroupTypeEnum = {
	main_group: 'main_group',
	subgroup: 'subgroup',
	exercise_group: 'exercise_group',
	filter_group: 'filter_group',
} as const

export type MuscleGroupMuscleGroupTypeEnumKey =
	(typeof muscleGroupMuscleGroupTypeEnum)[keyof typeof muscleGroupMuscleGroupTypeEnum]

export type MuscleGroup = {
	/**
	 * @description Unique identifier for the muscle group.
	 * @type string
	 */
	muscleGroupCode: string
	/**
	 * @description Split type for muscles / exercises
	 * @type string | undefined
	 */
	muscleSplitTarget?: MuscleSplitTarget | null
	/**
	 * @description The target number of sets for the week for this muscle group.
	 * @type integer | undefined
	 */
	WeeklySetTarget?: number
	/**
	 * @description Name of the muscle group, localized.
	 * @type string | undefined
	 */
	readonly muscleGroupName?: string
	/**
	 * @description parent group CODE for hierarchical structuring.
	 * @type string
	 */
	muscleGroupParent?: string | null
	/**
	 * @type array | undefined
	 */
	muscleGroupTranslations?: MuscleGroupTranslation[]
	/**
	 * @description An array of muscle codes associated with this muscle group. \nEach muscle code represents a specific muscle or muscle group targeted in exercises. \nThe codes are used to identify muscles across different languages and provide \nconsistency in muscle targeting for various exercises.\n
	 * @type array | undefined
	 */
	muscleGroupMuscles?: string[]
	/**
	 * @type string | undefined
	 */
	muscleGroupType?: MuscleGroupMuscleGroupTypeEnumKey
	/**
	 * @description Link to the thumbnail image for the muscle group.
	 * @type object | undefined
	 */
	muscleGroupThumbnail?: MediaAsset
}
