/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const muscleSplitTargetEnum = {
	Push: 'Push',
	Pull: 'Pull',
	Legs: 'Legs',
	Core: 'Core',
	Accessories: 'Accessories',
} as const

export type MuscleSplitTargetEnumKey =
	(typeof muscleSplitTargetEnum)[keyof typeof muscleSplitTargetEnum]

/**
 * @description Split type for muscles / exercises
 */
export type MuscleSplitTarget = MuscleSplitTargetEnumKey | null
