/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MuscleGroupTranslation = {
	/**
	 * @description The locale code for this translation (e.g., \'en-US\', \'es-ES\')
	 * @type string
	 */
	localeCode: string
	/**
	 * @description The translated name of the muscle group
	 * @type string
	 */
	muscleGroupName: string
	/**
	 * @description The translated description of the muscle group (optional)
	 * @type string | undefined
	 */
	muscleGroupDescription?: string
}
