/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const programDayTypeEnum = {
	Empty: 'Empty',
	Workout: 'Workout',
	Rest: 'Rest',
	Cardio: 'Cardio',
	ActiveRecovery: 'ActiveRecovery',
} as const

export type ProgramDayTypeEnumKey = (typeof programDayTypeEnum)[keyof typeof programDayTypeEnum]

/**
 * @description Represents the type of a workout program day.
 * @example Workout
 */
export type ProgramDayType = ProgramDayTypeEnumKey
