/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WorkoutMeta = {
	/**
	 * @description The date and time when the workout was started.
	 * @type string, date-time
	 */
	workoutLogStartedAt?: string | null
	/**
	 * @description The duration of the workout in seconds.
	 * @type integer, int32
	 */
	workoutLogDuration?: number | null
	/**
	 * @description The date and time when the workout timer was started.
	 * @type string, date-time
	 */
	workoutLogTimerStartedAt?: string | null
	/**
	 * @description The date and time when the workout was completed.
	 * @type string, date-time
	 */
	workoutLogEndedAt?: string | null
	/**
	 * @description Indicates if the workout log was automatically paused.
	 * @type boolean
	 */
	workoutLogAutoPaused?: boolean | null
}
