/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const workoutDataTypeEnum = {
	ExerciseVideo: 'ExerciseVideo',
	Callout: 'Callout',
	ExerciseList: 'ExerciseList',
	PendingSync: 'PendingSync',
} as const

export type WorkoutDataTypeEnumKey = (typeof workoutDataTypeEnum)[keyof typeof workoutDataTypeEnum]

/**
 * @description Represents a special type of workout data entry. Null for regular exercises.\n
 * @example ExerciseVideo
 */
export type WorkoutDataType = WorkoutDataTypeEnumKey | null
