/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const workoutAchievementAchievementTypeEnum = {
	PERSONAL_BEST_WEIGHT: 'PERSONAL_BEST_WEIGHT',
	PERSONAL_BEST_REPS: 'PERSONAL_BEST_REPS',
	PERSONAL_BEST_VOLUME: 'PERSONAL_BEST_VOLUME',
	PERSONAL_BEST_SET: 'PERSONAL_BEST_SET',
	WORKOUT_MILESTONE: 'WORKOUT_MILESTONE',
} as const

export type WorkoutAchievementAchievementTypeEnumKey =
	(typeof workoutAchievementAchievementTypeEnum)[keyof typeof workoutAchievementAchievementTypeEnum]

/**
 * @description A personal record or milestone earned during a completed workout.
 */
export type WorkoutAchievement = {
	/**
	 * @description The exercise code this achievement relates to.
	 * @type string | undefined
	 */
	exerciseCode?: string
	/**
	 * @description Display name of the exercise.
	 * @type string | undefined
	 */
	exerciseName?: string
	/**
	 * @description The category of achievement earned.
	 * @type string | undefined
	 */
	achievementType?: WorkoutAchievementAchievementTypeEnumKey
	/**
	 * @description The specific measurement code (e.g. WEIGHT, REPS) for measurement-level PRs.
	 * @type string
	 */
	measurementCode?: string | null
	/**
	 * @description The new personal record value achieved.
	 * @type number | undefined, double
	 */
	newValue?: number
	/**
	 * @description The previous personal best value, if one existed.
	 * @type number, double
	 */
	previousValue?: number | null
	/**
	 * @description The unit of measurement for display purposes.
	 * @type string
	 */
	unit?: string | null
}
