/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatorProfile } from './CreatorProfile.ts'
import type { WorkoutSummary } from './WorkoutSummary.ts'
import type { WorkoutType } from './WorkoutType.ts'

/**
 * @description Represents the source of a workout log.
 */
export type WorkoutSource = {
	/**
	 * @description Unique identifier for the workout.
	 * @type string | undefined, uuid
	 */
	workoutId?: string
	/**
	 * @description Unique identifier for the source workout, log, or program.
	 * @type string | undefined, uuid
	 */
	sourceId?: string
	/**
	 * @description The day number of the program that this workout log is associated with.
	 * @type integer | undefined
	 */
	programDayNumber?: number
	/**
	 * @description The week number of the program that this workout log is associated with.
	 * @type integer | undefined
	 */
	programWeekNumber?: number
	/**
	 * @description Name of the source workout.
	 * @type string | undefined
	 */
	sourceTitle?: string
	/**
	 * @description Description of the source workout.
	 * @type string | undefined
	 */
	sourceDescription?: string
	/**
	 * @description Type of the source workout.
	 * @type string | undefined
	 */
	sourceType?: WorkoutType | null
	/**
	 * @description Represents a creator\'s profile information.
	 * @type object | undefined
	 */
	sourceCreatorProfile?: CreatorProfile
	/**
	 * @description Summary information about the workout.
	 * @type object | undefined
	 */
	sourceWorkoutSummary?: WorkoutSummary
}
