/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { WorkoutAchievement } from './WorkoutAchievement.ts'

export type WorkoutAchievementList = WorkoutAchievement[] | null
