/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Analytics data for the workout.
 */
export type WorkoutAnalytics = {
	/**
	 * @description Number of views for the workout.
	 * @type integer | undefined
	 */
	totalViews?: number
	/**
	 * @description The average rating of the workout.
	 * @type number | undefined, float
	 */
	ratingAverage?: number
	/**
	 * @description The number of ratings for the workout.
	 * @type number | undefined, int
	 */
	ratingCount?: number
}
