/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BaseWorkout } from './BaseWorkout.ts'
import type { MediaAsset } from './MediaAsset.ts'
import type { MediaAssetList } from './MediaAssetList.ts'
import type { ProgramDayType } from './ProgramDayType.ts'
import type { WorkoutAchievementList } from './WorkoutAchievementList.ts'
import type { WorkoutAnalytics } from './WorkoutAnalytics.ts'
import type { WorkoutMeta } from './WorkoutMeta.ts'
import type { WorkoutSource } from './WorkoutSource.ts'
import type { WorkoutType } from './WorkoutType.ts'

export type Workout = WorkoutMeta &
	BaseWorkout & {
		/**
		 * @description Unique identifier for the workout.
		 * @type string | undefined, uuid
		 */
		workoutId?: string
		/**
		 * @description Type of the source workout.
		 * @type string
		 */
		workoutType: WorkoutType | null
		/**
		 * @description ID of the original workout this was referenced from.
		 * @type string, uuid
		 */
		sourceWorkoutId?: string | null
		/**
		 * @description Order-stable fingerprint of the workout\'s exercise shape when it began (real exercise codes ordered by exerciseOrder, joined with \"|\"). Only set when the workout was started from another workout. Used to recognise a repeated workout and compare its stats.\n
		 * @type string
		 */
		startingExerciseSerial?: string | null
		/**
		 * @description Order-stable fingerprint of the workout\'s exercise shape at completion (real exercise codes ordered by exerciseOrder, joined with \"|\"). Set when the workout is finished.\n
		 * @type string
		 */
		finalExerciseSerial?: string | null
		/**
		 * @description The main image representing the workout.
		 * @type object | undefined
		 */
		workoutBackgroundImage?: MediaAsset
		/**
		 * @description Unique identifier for the workout background image.
		 * @type string | undefined, uuid
		 */
		workoutBackgroundImageId?: string
		/**
		 * @description URL of where we can find this workout on the rest of the internet.
		 * @type string
		 */
		workoutSourceUrl?: string | null
		/**
		 * @description Indicates if the workout is a user\'s own workout or a bookmarked one from another user.
		 * @type boolean | undefined
		 */
		isBookmark?: boolean
		/**
		 * @description NOT IMPLEMENTED:- TODO- List of tags associated with the workout.
		 * @type array | undefined
		 */
		workoutTags?: string[]
		/**
		 * @description The date and time when the workout was last used.
		 * @type string, date-time
		 */
		lastViewedAt?: string | null
		/**
		 * @description Analytics data for the workout.
		 * @type object | undefined
		 */
		workoutAnalytics?: WorkoutAnalytics
		/**
		 * @type array | undefined
		 */
		workoutMedia?: MediaAssetList
		/**
		 * @description Represents the source of a workout log.
		 * @type object | undefined
		 */
		workoutSource?: WorkoutSource
		/**
		 * @description Personal records and milestones earned when this workout was completed.
		 * @type array | undefined
		 */
		readonly workoutAchievements?: WorkoutAchievementList | null
		/**
		 * @description Number of claps the current user or anonymous session has given this workout log
		 * @type integer
		 */
		userClaps?: number | null
		/**
		 * @description Indicates if this feed item should be shown in the main feed
		 * @type boolean | undefined
		 */
		showInFeed?: boolean
		/**
		 * @description Total number of claps for this workout log
		 * @type integer
		 */
		totalClaps?: number | null
		/**
		 * @description Unique identifier for the program.
		 * @type string | undefined, uuid
		 */
		workoutProgramId?: string
		/**
		 * @description The day number within the program week.
		 * @type integer | undefined
		 */
		dayNumber?: number
		/**
		 * @description The week number within the program.
		 * @type integer | undefined
		 */
		weekNumber?: number
		/**
		 * @description Represents the type of a workout program day.
		 * @type string | undefined
		 */
		programDayType?: ProgramDayType
	}
