/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const workoutTypeEnum = {
	Template: 'Template',
	ProgramDay: 'ProgramDay',
	Log: 'Log',
} as const

export type WorkoutTypeEnumKey = (typeof workoutTypeEnum)[keyof typeof workoutTypeEnum]

/**
 * @description Type of the source workout.
 */
export type WorkoutType = WorkoutTypeEnumKey | null
