/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Summary information about the workout.
 */
export type WorkoutSummary = {
	/**
	 * @description Total number of repetitions across all exercises in the workout.
	 * @type integer | undefined
	 */
	totalReps?: number
	/**
	 * @description Total number of sets across all exercises in the workout.
	 * @type integer | undefined
	 */
	totalSets?: number
	/**
	 * @description Total volume (weight * reps) across all exercises in the workout.
	 * @type number | undefined, float
	 */
	totalVolume?: number
	/**
	 * @description Total distance covered in the workout, if applicable.
	 * @type number | undefined, float
	 */
	totalDistance?: number
	/**
	 * @description Estimated duration of the workout in minutes.
	 * @type integer | undefined
	 */
	estimatedDuration?: number
	/**
	 * @description Number of exercises in the workout.
	 * @type integer | undefined
	 */
	exerciseCount?: number
}
